@echo off
echo Stopping any running Next.js processes...
taskkill /f /im node.exe 2>nul

echo Clearing Next.js cache...
if exist .next rmdir /s /q .next

echo Clearing node_modules cache...
if exist node_modules\.cache rmdir /s /q node_modules\.cache

echo Starting development server with optimizations...
npm run dev
